# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Z:\SourFace\GUI\visualisation.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(886, 359)
        MainWindow.setStyleSheet("font: 10pt \"Century Gothic\";\n"
"background-color:rgb(43, 43, 43);\n"
"color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(29, 9, 763, 298))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        self.salty_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.salty_bar.setProperty("value", 24)
        self.salty_bar.setObjectName("salty_bar")
        self.gridLayout_3.addWidget(self.salty_bar, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 4, 0, 1, 1)
        self.bitter_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.bitter_bar.setStyleSheet("QProgressBar {\n"
"     background-color: rgb(200, 200, 200);\n"
" }")
        self.bitter_bar.setProperty("value", 24)
        self.bitter_bar.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing)
        self.bitter_bar.setTextVisible(True)
        self.bitter_bar.setOrientation(QtCore.Qt.Horizontal)
        self.bitter_bar.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.bitter_bar.setObjectName("bitter_bar")
        self.gridLayout_3.addWidget(self.bitter_bar, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.umami_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.umami_bar.setProperty("value", 24)
        self.umami_bar.setObjectName("umami_bar")
        self.gridLayout_3.addWidget(self.umami_bar, 5, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 1)
        self.sweet_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.sweet_bar.setProperty("value", 24)
        self.sweet_bar.setObjectName("sweet_bar")
        self.gridLayout_3.addWidget(self.sweet_bar, 4, 1, 1, 1)
        self.sour_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sour_bar.sizePolicy().hasHeightForWidth())
        self.sour_bar.setSizePolicy(sizePolicy)
        self.sour_bar.setProperty("value", 24)
        self.sour_bar.setObjectName("sour_bar")
        self.gridLayout_3.addWidget(self.sour_bar, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setStyleSheet("\n"
"font: 75 14pt \"Century Gothic\";\n"
"font-weight: bold;\n"
"color:rgb(200, 200, 200);")
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 0, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.gridLayout_3.addItem(spacerItem, 6, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_3)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 5, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.disgust_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.disgust_bar.setProperty("value", 24)
        self.disgust_bar.setObjectName("disgust_bar")
        self.gridLayout_4.addWidget(self.disgust_bar, 6, 1, 1, 1)
        self.happy_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.happy_bar.setProperty("value", 24)
        self.happy_bar.setObjectName("happy_bar")
        self.gridLayout_4.addWidget(self.happy_bar, 1, 1, 1, 1)
        self.suprise_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.suprise_bar.setProperty("value", 24)
        self.suprise_bar.setObjectName("suprise_bar")
        self.gridLayout_4.addWidget(self.suprise_bar, 3, 1, 1, 1)
        self.anger_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.anger_bar.setProperty("value", 24)
        self.anger_bar.setObjectName("anger_bar")
        self.gridLayout_4.addWidget(self.anger_bar, 5, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.sad_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.sad_bar.setProperty("value", 24)
        self.sad_bar.setObjectName("sad_bar")
        self.gridLayout_4.addWidget(self.sad_bar, 2, 1, 1, 1)
        self.fear_bar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.fear_bar.setProperty("value", 24)
        self.fear_bar.setObjectName("fear_bar")
        self.gridLayout_4.addWidget(self.fear_bar, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 5, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setStyleSheet("font: 75 14pt \"Century Gothic\";\n"
"font-weight: bold;\n"
"color:rgb(200, 200, 200);")
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 2)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_4.addWidget(self.label_13, 6, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 1, 6, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 886, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_7.setText(_translate("MainWindow", "Video"))
        self.label_5.setText(_translate("MainWindow", "Umami"))
        self.label.setText(_translate("MainWindow", "Sour"))
        self.label_4.setText(_translate("MainWindow", "Sweet"))
        self.label_2.setText(_translate("MainWindow", "Bitter"))
        self.label_3.setText(_translate("MainWindow", "Salty"))
        self.label_15.setText(_translate("MainWindow", "Taste Detected: "))
        self.label_9.setText(_translate("MainWindow", "Happiness/Joy"))
        self.label_8.setText(_translate("MainWindow", "Sadness"))
        self.label_11.setText(_translate("MainWindow", "Fear"))
        self.label_10.setText(_translate("MainWindow", "Surprise"))
        self.label_12.setText(_translate("MainWindow", "Anger"))
        self.label_16.setText(_translate("MainWindow", "Emotion Detected: "))
        self.label_13.setText(_translate("MainWindow", "Disgust"))


